import type { Metadata } from "next";
import "./globals.scss";
import * as Layouts from "@/app/components/layouts/index";

export const metadata: Metadata = {
    title: "ともきちの旅行ブログ｜旅の最新情報をお届け",
    description: "Generated by create next app",
};

export default function RootLayout({
  	children,
}: Readonly<{
  	children: React.ReactNode;
}>) {
  	return (
    	<html lang="ja">
      		<body>
				<Layouts.Header />
        			{children}
				<Layouts.Footer />
      		</body>
    	</html>
  	);
};
